#+TITLE: Doom Emacs Config
#+AUTHOR: Andrea Esposito
#+PROPERTY: header-args :tangle yes :comments both

* Table of Contents :TOC:
- [[#introduction][Introduction]]
- [[#basic-variables-and-configs][Basic Variables and Configs]]
  - [[#themes][Themes]]
  - [[#fix-evil-mode-navigation][Fix EVIL mode navigation]]
- [[#org-mode][Org Mode]]
  - [[#allowing-citations][Allowing Citations]]
  - [[#latex-export][LaTeX Export]]
  - [[#org-mode-babel][Org-Mode Babel]]
  - [[#org-capture-templates][Org Capture Templates]]
  - [[#writing-letters][Writing Letters]]
- [[#additional-stuff][Additional Stuff]]
- [[#mail-mu4e][Mail (mu4e)]]
  - [[#using-org-mode][Using Org-Mode]]
  - [[#accounts-setup][Accounts Setup]]
- [[#telegram][Telegram]]
- [[#olivetti-mode][Olivetti mode]]
- [[#screenwriting-fountain-mode][Screenwriting (=fountain-mode=)]]
- [[#latex][LaTeX]]
- [[#python][Python]]
  - [[#ruff-and-ruff-language-server][Ruff and Ruff Language Server]]

* Introduction
#+BEGIN_INFO
The content of this documentation comes directly from Doom Emacs' default configuration's comments.
#+END_INFO

#+BEGIN_SRC elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+END_SRC

This is, instead, the original documentation of Doom Emacs =packages.el= file.

#+BEGIN_SRC elisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;; (package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;; (package! another-package
;;   :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;; (package! this-package
;;   :recipe (:host github :repo "username/repo"
;;            :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;; (package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;; (package! builtin-package :recipe (:nonrecursive t))
;; (package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;; (package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;; (package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;; (unpin! pinned-package)
;; ...or multiple packages
;; (unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;; (unpin! t)
;(package! smart-tabs-mode)
;(package! company-posframe)
#+END_SRC


* Basic Variables and Configs
Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!

The following line can be used on macOS to remove the title bar and make the
application window "rounded" (as other macOS apps). This looks especially good
if used with tiling window managers (e.g., yabai).
#+BEGIN_SRC elisp
(add-to-list 'default-frame-alist '(undecorated-round . t))
#+END_SRC


Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. It is optional.
#+BEGIN_SRC elisp
(setq user-full-name "Andrea Esposito"
      user-mail-address "esposito_andrea99@hotmail.com")
(setq gnutls-min-prime-bits 512)
#+end_src

** Themes
 Doom exposes five (optional) variables for controlling fonts in Doom:

 - `doom-font' -- the primary font to use
 - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
 - `doom-big-font' -- used for `doom-big-font-mode'; use this for
   presentations or streaming.
 - `doom-symbol-font' -- for symbols
 - `doom-serif-font' -- for the `fixed-pitch-serif' face

 See 'C-h v doom-font' for documentation and more examples of what they
 accept. For example:

#+BEGIN_SRC elisp
;; (setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
#+END_SRC

 If you or Emacs can't find your font, use 'M-x describe-font' to look them
 up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
 refresh your font settings. If Emacs still can't find your font, it likely
 wasn't installed correctly. Font issues are rarely Doom issues!

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. The default is =doom-one=.

#+begin_src elisp
(setq doom-theme 'doom-dracula)
#+end_src

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For absolute line numbers, set this to `t'. For relative line numbers, set this to `relative'.
#+begin_src elisp
(setq display-line-numbers-type 'relative)
#+end_src

Whenever you reconfigure a package, make sure to wrap your config in an
`after!' block, otherwise Doom's defaults may override your settings. E.g.
#+BEGIN_SRC elisp :tangle no
  (after! PACKAGE
    (setq x y))
#+END_SRC
The exceptions to this rule:
  - Setting file/directory variables (like `org-directory')
  - Setting variables which explicitly tell you to set them before their
    package is loaded (see 'C-h v VARIABLE' to look up their documentation).
  - Setting doom variables (which start with 'doom-' or '+').
Here are some additional functions/macros that will help you configure Doom.
- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.
- `map!' for binding new keys
To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.
Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
etc).
You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.

** Fix EVIL mode navigation
For some reasons, =g j=, =g k=, etc. do not work (especially in Org-Mode) due to some clash with other shortcuts, and I should use =g <up>=, =g <down>=. This is really not confortable. Instead of trying and finding /where/ the clash is, it's just easier to remap the bindings to use visual lines.
#+begin_src elisp
(map!
 :nvm "k"   #'evil-previous-visual-line
 :o   "k"   #'evil-previous-line
 :nvm "j" #'evil-next-visual-line
 :o   "j" #'evil-next-line
 :nvm "<home>" #'evil-beginning-of-visual-line
 :nvm "<end>"  #'evil-end-of-visual-line)
#+end_src
** macOS specific stuff
Nowadays I mostly use macOS. These options make Emacs work better with the typical macOS workflow. I use Mr. Yamamoto port, installed using
#+BEGIN_SRC sh :tangle no
brew tap d12frosted/emacs-plus
brew install emacs-plus
#+END_SRC

*** Using "native" full screen
By default, Emacs is set to fullscreen by simply making itself as big as possible. This doesn't really play nicely with the notch and Spaces and Mission Control. Setting the following variable to =true= will force Emacs to use native full screen by default.
#+BEGIN_SRC elisp
(setq ns-use-native-fullscreen t)
#+END_SRC
I can now use ~toggle-frame-fullscreen~ (mapped to =SPC t F=) to toggle fullscreen as a typical macOS app.

Additionally, I want to use the left "option" key as "meta" and the right one as "option" to input special characters.
#+begin_src elisp
(setq ns-alternate-modifier 'meta)
(setq ns-right-alternate-modifier 'none)
#+end_src

* Org Mode
#+begin_src elisp
;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/Documents/Org")


;; Set the output theme of HTML code to CSS, thus making it dependent on the
;; actual stylesheet used.
(setq org-html-htmlize-output-type 'css)
#+END_SRC

I prefer tags to be aligned to the right.
#+BEGIN_SRC elisp
(setq fill-column 80)
(setq org-tags-column (- fill-column))
#+END_SRC

This automatically sets =.org_archive= files as =org-mode= files, regardless of the presence (or absence) of a mode line.
#+begin_src elisp
(add-to-list 'auto-mode-alist '("\\.org_archive\\'" . org-mode))
#+end_src

** Obsidian
I use =obsidian.el= to edit Obsidian.md files in Emacs. This fits in the "Org-Mode" category since in Obsidian I have an org-mode plugin so the two play nicely together.

#+begin_src elisp :tangle packages.el
(package! obsidian)
#+end_src

And I add =md-roam= (currently not available on MELPA) to make =org-roam= work also with Obsidian's markdown files.
#+begin_src elisp :tangle packages.el
(package! md-roam
  :recipe (:host github :repo "nobiot/md-roam"))
#+end_src

#+begin_src elisp
(use-package! org-roam
  :after org
  ; :config
  ; (setq org-roam-directory "/path/to/valut")
  ; (setq org-roam-dailies-directory "Journal/")
)
(use-package! md-roam
  :after org-roam
  :config
  (set-company-backend! 'markdown-mode 'company-capf) ; add company-capf as company backend in markdown buffers
  (setq org-roam-file-extensions '("org" "md")) ; enable Org-roam for a markdown files
  (md-roam-mode 1) ; md-roam-mode needs to be active before org-roam-db-sync
  (org-roam-db-autosync-mode 1)
  (add-to-list 'org-roam-capture-templates
               '("m" "Markdown" plain "" :target
                 (file+head "%<%Y-%m-%dT%H%M%S>-${slug}.md"
                            "---\ntitle: ${title}\nid: %<%Y-%m-%dT%H%M%S>\ncategory: \n---\n")
                 :unnarrowed t)))
#+end_src

** Allowing Citations
This package allows citing from BibTeX. We must install it first...
#+BEGIN_SRC elisp :tangle packages.el
(package! org-ref)
#+END_SRC
... and then require it.
#+BEGIN_SRC elisp
(require 'org-ref)
#+END_SRC

** LaTeX Export
This sets the LaTeX compiler to use latexmk and use =minted= to colorize source code listings.
#+BEGIN_SRC elisp
; (after! ox-latex
;   (setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f")))
(add-to-list 'org-latex-packages-alist '("" "minted"))
(setq org-latex-listings 'minted)
#+END_SRC

When I export to PDF from Org-Mode using LaTeX, I don't need the =.tex= file (if I need to manually inspect or edit it, I just convert to tex first and then manually compile). Furthermore, I don't want any natbib/biblatex =.bbl= files. So I tell Org-Mode that they are "temporary log files"...
#+BEGIN_SRC elisp
(after! ox-latex
    (add-to-list 'org-latex-logfiles-extensions "tex")
    (add-to-list 'org-latex-logfiles-extensions "bbl"))
#+END_SRC

*** Custom LaTeX Classes
**** Personal Notes
This class is heavily inspired by O'Reilly books (requires LaTeX =.cls= file in the same directory of the =.org= file). I usually use it for personal notes (for example, I used it for writing notes during AI courses).
#+BEGIN_SRC elisp
(after! ox-latex
  (add-to-list 'org-latex-classes
               '("notes"
                 "\\documentclass{mynotes}
\\usepackage[utf8]{inputenc}
[NO-DEFAULT-PACKAGES]"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+END_SRC
**** ACM
This class uses ACM =acmart= class (requires LaTeX =.cls= file in the same directory of the =.org= file).
#+BEGIN_SRC elisp
(after! ox-latex
  (add-to-list 'org-latex-classes
               '("acm"
                 "\\documentclass{acmart}
\\usepackage[utf8]{inputenc}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage[normalem]{ulem}
\\usepackage{soul}
[NO-DEFAULT-PACKAGES]"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+END_SRC
**** Springer LNCS
This class uses Springer LNCS class (requires LaTeX =.cls= file in the same directory of the =.org= file).
#+BEGIN_SRC elisp
(after! ox-latex
  (add-to-list 'org-latex-classes
               '("lncs"
                 "\\documentclass{llncs}
\\usepackage[utf8]{inputenc}
\\usepackage{graphicx}
\\usepackage{hyperref}
[NO-DEFAULT-PACKAGES]"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+END_SRC
**** CEUR-WS
This class uses CEUR-WS =ceurart= class (requires LaTeX =.cls= file in the same directory of the =.org= file).
#+BEGIN_SRC elisp
(after! ox-latex
  (add-to-list 'org-latex-classes
                 '("ceurart" "\\documentclass{ceurart}
\\usepackage[utf8]{inputenc}
\\usepackage{graphicx}
\\usepackage{hyperref}
[NO-DEFAULT-PACKAGES]
\\sloppy"
                   ("\\section{%s}" . "\\section*{%s}")
                   ("\\subsection{%s}" . "\\subsection*{%s}")
                   ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                   ("\\paragraph{%s}" . "\\paragraph*{%s}")
                   ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+END_SRC
**** APA
This class uses APA compliant styles.
#+BEGIN_SRC elisp
(after! ox-latex
  (add-to-list 'org-latex-classes
               '("apa"
                 "\\documentclass{apa7}
\\usepackage{xcolor}
\\usepackage{amsmath,amsthm,amssymb}
\\newtheorem{definition}{Definition}
[DEFAULT-PACKAGES]
[EXTRA]
\\usepackage{cleveref}
%\\usepackage{abstract}
\\usepackage{hyperref}
\\hypersetup{colorlinks=true,allcolors=blue}
"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+END_SRC
**** CVPR
This class uses CVPR compliant styles.
#+BEGIN_SRC elisp
(after! ox-latex
  (add-to-list 'org-latex-classes
               '("cvpr"
                 "\\documentclass[10pt,twocolumn,letterpaper]{article}
\\usepackage{cvpr}
\\usepackage{times}
\\usepackage{epsfig}
\\usepackage{graphicx}
\\usepackage{amsmath}
\\usepackage{amssymb}
[NO-DEFAULT-PACKAGES]
"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+END_SRC

** Org-Mode Babel
*** Additional Languages
**** Mermaid for charts
#+BEGIN_SRC elisp :tangle packages.el
(package! ob-mermaid)
#+END_SRC

#+BEGIN_SRC elisp
(org-babel-do-load-languages
    'org-babel-load-languages
    '((mermaid . t)
      (scheme . t)
      (your-other-langs . t)))
#+END_SRC

** Org Capture Templates

I was fine with Doom Emacs' default templates, until I was not. I liked the overall settings, but I did not find confortable to use different files that all behave like an inbox, and it felt "wrong" to mix unprocessed inbox elements with processed tasks (e.g., in the =projects.org= file). Here I try to set everything up using only a single file =inbox.org=.

For this purpose, we start by defining a "common inbox" file name (this is used to simplify any editing if I need it in the future).
#+BEGIN_SRC elisp
(setq +org-capture-common-inbox-file "~/Documents/Org/inbox.org")
#+END_SRC

We then assign all Doom Emacs' =org-capture= variables the value of the common inbox file name.
#+BEGIN_SRC elisp
(setq +org-capture-todo-file +org-capture-common-inbox-file)
(setq +org-capture-changelog-file +org-capture-common-inbox-file)
(setq +org-capture-notes-file +org-capture-common-inbox-file)
;; I like the journal file to be kept separate
;; (setq +org-capture-journal-file +org-capture-common-inbox-file)
(setq +org-capture-projects-file +org-capture-common-inbox-file)
(setq +org-capture-emails-file +org-capture-common-inbox-file)
#+END_SRC
** Writing Letters
#+BEGIN_SRC elisp :tangle packages.el
(package! ox-koma-letter :recipe
  (:host github
   :repo "bzg/org-mode"
   :files ("lisp/ox-koma-letter.el")))
#+END_SRC

#+BEGIN_SRC elisp
(eval-after-load 'ox '(require 'ox-koma-letter))
#+END_SRC

** Custom TOOD states
*** Workflow for papers and articles

Here I define a new workflow for a "PAPER" that should follow this pipeline:
1. When the paper is ideated or assigned, it is noted as PAPER
2. When started working on it, it is in WRITING
3. When the paper is ready and is sent for review, it is INREVIEW
4. When the paper is got back from reviews:
   1. If the paper is being rejected it goes into REJECTED
   2. If edits are required, it goes to TOEDIT
      1. Once ready and sent out again, it gets back to INREVIEW
   3. If the paper is accepted, it is marked as ACCEPTED
      1. Once proof are ready and are received and must be checked, it becomes PROOF
      2. Once proof are sent out it becomes INPRESS
      3. One published it becomes PUBLISHED
#+BEGIN_SRC elisp 
(add-to-list 'org-todo-keywords
        '(sequence
           "PAPER(P)"  ; A paper, which is in itself a type of project
           "WRITING(W)"  ; The paper has been started
           "INREVIEW(R)"  ; The paper was sent for review and we are waiting for reviews
           "TOEDIT(E)"  ; The paper was received back from review and edits should be made
           "ACCEPTED(A)"  ; The paper was accepted
           "PROOF(I)"  ; Proofs need to be checked
           "INPRESS(S)"  ; Proofs were checked and the paper is now in press
           "|"
           "REJECTED(K)"  ; The paper was rejected
           "PUBLISHED(D") ; The paper was accepted and is now published
        t
          )
#+END_SRC

We can now color-code the various keywords...
#+BEGIN_SRC elisp
(add-to-list 'org-todo-keyword-faces '("WRITING" . +org-todo-active))
(add-to-list 'org-todo-keyword-faces '("INREVIEW"  . +org-todo-onhold))
(add-to-list 'org-todo-keyword-faces '("ACCEPTED" . +org-todo-onhold))
(add-to-list 'org-todo-keyword-faces '("INPRESS" . +org-todo-onhold))
(add-to-list 'org-todo-keyword-faces '("PAPER" . +org-todo-project))
(add-to-list 'org-todo-keyword-faces '("REJECTED"   . +org-todo-cancel))
#+END_SRC
** System-Wide Org Capture
Code from: https://macowners.club/posts/org-capture-from-everywhere-macos/#default-org-capture

#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! noflet)
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle yes
(defun timu-func-make-capture-frame ()
  "Create a new frame and run `org-capture'."
  (interactive)
  (unless (server-running-p)
    (server-start))
  (require 'noflet)
  (make-frame '((name . "capture")
                (t . 80)
                (height . 25)))
  (select-frame-by-name "capture")
  (delete-other-windows)
  (noflet ((switch-to-buffer-other-window (buf) (switch-to-buffer buf)))
    (org-capture)))

(defadvice org-capture-finalize
    (after delete-capture-frame activate)
  "Advise capture-finalize to close the frame."
  (if (equal "capture" (frame-parameter nil 'name))
      (delete-frame)))

(defadvice org-capture-destroy
    (after delete-capture-frame activate)
  "Advise capture-destroy to close the frame."
  (if (equal "capture" (frame-parameter nil 'name))
      (delete-frame)))
#+end_src

#+RESULTS:
: org-capture-destroy

* Additional Stuff
#+BEGIN_SRC elisp
(display-battery-mode t)
(setq display-time-string-forms '(year "." month "." day " " 24-hours ":" minutes))
(display-time)
#+END_src

* Mail (mu4e)
#+begin_src elisp
(after! mu4e
  (setq sendmail-program (executable-find "msmtp")
        send-mail-function #'smtpmail-send-it
        message-sendmail-f-is-evil t
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-send-mail-function #'message-send-mail-with-sendmail))
#+end_src
#+BEGIN_SRC elisp
(after! mu4e
(setq mu4e-compose-format-flowed t)
;; (remove-hook! 'mu4e-compose-pre-hook #'org-msg-mode)
;; (add-hook! 'mu4e-compose-mode-hook #'message-mode)
;; (setq mm-sign-option 'guided)
;; (setq mu4e-sent-messages-behavior (lambda ()
                                    ;; (if (string= (message-sendmail-envelope-from) "a.esposito39@studenti.uniba.it")
                                        ;; 'delete 'sent)))
;; (add-hook! 'mu4e-compose-mode-hook #'turn-on-auto-fill)

(setq mu4e-headers-date-format "%+4Y-%m-%d")
(with-eval-after-load 'mm-decode
    (add-to-list 'mm-discouraged-alternatives "text/html"))
(setq mu4e-view-html-plaintext-ratio-heuristic most-positive-fixnum)
(setq mu4e-context-policy 'always-ask)
;; (add-hook 'mu4e-compose-mode-hook 'flyspell-mode)
(setq mu4e-maildir-shortcuts '(("/uniba/Inbox" . ?u)
                               ("/hotmail/Inbox" . ?h)
                               ))
                               ;; ("/studentiuniba/Inbox" . ?s)
(setq mu4e-compose-format-flowed t)
(add-to-list 'mu4e-bookmarks
               '(:name "All Inboxes" :query "m:/hotmail/Inbox or m:/uniba/Inbox" :key ?i))

(add-to-list 'display-buffer-alist
             `(,(regexp-quote mu4e-main-buffer-name)
               display-buffer-same-window))
)
#+END_SRC

** Using Org-Mode
#+BEGIN_SRC elisp :tangle packages.el
(package! org-mime)
;; (package! org-msg :disable t)
;; (package! org-msg)
#+END_SRC

#+BEGIN_SRC elisp
(use-package org-mime
  :ensure t)

(setq org-mime-export-options '(:with-toc nil))
#+END_SRC

** Accounts Setup
*** Personal Account (Hotmail/Outlook)
#+BEGIN_SRC elisp
(set-email-account! "Hotmail"
  '((mu4e-sent-folder       . "/hotmail/Sent")
    (mu4e-drafts-folder     . "/hotmail/Drafts")
    (mu4e-trash-folder      . "/hotmail/Deleted")
    (mu4e-refile-folder     . "/hotmail/Archive")
    ; (mu4e-get-mail-command  . "mbsync -a")
    (mu4e-update-interval   . 60)
    (smtpmail-smtp-user     . "esposito_andrea99@hotmail.com")
    (user-mail-address      . "esposito_andrea99@hotmail.com")    ;; only needed for mu < 1.4
    (smtpmail-stream-type   . starttls)
    (smtpmail-smtp-server . "smtp.office365.com")
    (smtpmail-smtp-service . 587)
    (mu4e-compose-signature . (concat "Andrea Esposito, Ph.D.\n"
                                      "Research Fellow (he/him/his)\n"
                                      "\n"
                                      "University of Bari Aldo Moro\n"
                                      "Department of Computer Science\n"
                                      "I.V.U. Laboratory\n"
                                      "Via E. Orabona 4, 70125 Bari, Italy (4th floor)\n"
                                      "\n"
                                      "eMail: andrea.esposito@uniba.it\n"
                                      "Web: https://espositoandrea.github.io\n"
                                      "ORCID: 0000-0002-9536-3087\n"
                                      "Tel.: +39 080 5442461\n" )))
  t)
#+END_SRC
*** Work Account (University of Bari)
#+BEGIN_SRC elisp
(set-email-account! "UniBa"
  '((mu4e-sent-folder       . "/uniba/Sent")
    (mu4e-drafts-folder     . "/uniba/Drafts")
    (mu4e-trash-folder      . "/uniba/Trash")
    (mu4e-refile-folder     . "/uniba/Archive")
    ;; (mu4e-get-mail-command  . "mbsync -a")
    (mu4e-update-interval   . 60)
    (smtpmail-smtp-user     . "andrea.esposito")
    (user-mail-address      . "andrea.esposito@uniba.it")    ;; only needed for mu < 1.4
    (smtpmail-stream-type   . starttls)
    (smtpmail-smtp-server . "smtp.uniba.it")
    (smtpmail-smtp-service . 587)
    (mu4e-compose-signature . (concat "Andrea Esposito, Ph.D.\n"
                                      "Research Fellow (he/him/his)\n"
                                      "\n"
                                      "University of Bari Aldo Moro\n"
                                      "Department of Computer Science\n"
                                      "I.V.U. Laboratory\n"
                                      "Via E. Orabona 4, 70125 Bari, Italy (4th floor)\n"
                                      "\n"
                                      "eMail: andrea.esposito@uniba.it\n"
                                      "Web: https://espositoandrea.github.io\n"
                                      "ORCID: 0000-0002-9536-3087\n"
                                      "Tel.: +39 080 5442461\n" )))
  t)
#+END_SRC

*** University Account (Student) [OLD]
#+BEGIN_SRC elisp :tangle no
(set-email-account! "Studenti UniBa"
  '((mu4e-trash-folder      . "/studentiuniba/[Gmail]/Cestino")
    (mu4e-refile-folder     . "/studentiuniba/[Gmail]/Archivio")
    (mu4e-drafts-folder     . "/studentiuniba/[Gmail]/Bozze")
    (mu4e-sent-folder       . "/studentiuniba/[Gmail]/Posta inviata")
    (mu4e-get-mail-command  . "mbsync -a")
    (mu4e-update-interval   . 60)
    (smtpmail-smtp-user     . "a.esposito39@studenti.uniba.it")
    (user-mail-address      . "a.esposito39@studenti.uniba.it")    ;; only needed for mu < 1.4
    (smtpmail-stream-type   . starttls)
    (smtpmail-smtp-server . "smtp.gmail.com")
    (smtpmail-smtp-service . 587)
    (mu4e-compose-signature . (concat "Andrea Esposito, Ph.D.\n"
                                      "Master’s student in Computer Science\n"
                                      "\n"
                                      "University of Bari “Aldo Moro”\n"
                                      "Department of Computer Science\n"
                                      "Degree Course in Computer Science\n"
                                      "\n"
                                      "Student ID: 735116\n"
                                      "ORCID: 0000-0002-9536-3087\n"
                                      "Personal Home Page: https://espositoandrea.github.io/")))
  t)

#+END_SRC

* Telegram
The Telegram config is currently /disabled/ since I don't need it for now...
To use it, one should first install this package:
#+BEGIN_SRC elisp :tangle no
(package! telega)
#+END_SRC

This is my configuration.
#+BEGIN_SRC elisp :tangle no
(defun my-telega-chat-mode ()
  (set (make-local-variable 'company-backends)
       (append (list 'telega-company-emoji
                   'telega-company-username
                   'telega-company-botcmd
                   'telega-company-hashtag)
             (when (telega-chat-bot-p telega-chatbuf--chat)
               '(telega-company-botcmd))))
  (company-mode 1))

(add-hook 'telega-chat-mode-hook 'my-telega-chat-mode)

(setq telega-use-images t
      telega-emoji-font-family "Ubuntu")
(telega-notifications-mode 1)
(add-to-list 'evil-emacs-state-modes 'telega-chat-mode)
(add-hook 'telega-chat-mode-hook
  (lambda ()
   (local-set-key (kbd "C-c q") 'telega)))

(map! :leader :desc "Open Telegram client" "o t" #'telega)
(require 'company-posframe)
(company-posframe-mode 1)

(map! :leader :desc "Open Telegram client" "o t" #'telega)
#+end_src

* Olivetti mode
#+BEGIN_SRC elisp :tangle packages.el
(package! olivetti)
#+END_SRC

#+BEGIN_SRC elisp
(map! :leader :desc "Toggle Olivetti mode" "t o"  #'olivetti-mode)
#+END_SRC

* Screenwriting (=fountain-mode=)
I do not typically screenwrite. However, sometimes it is useful to typeset something so that it /looks like/ a script. As an example, I often find myself transcribing interviews for research purposes and later analysis: typesetting it as a script allows for a "pleasurable" on-paper analysis, while using a "standard" markup language allows to easily parse it for usage in code.

A markup language for screenwriters if [[https://fountain.io][Fountain]].  To use within Emacs, one must install =fountain-mode=.

#+BEGIN_SRC elisp :tangle packages.el
(package! fountain-mode)
#+END_SRC

I can then simplify exporting to other formats by defining some mode-specific key bindings to be used instead of =C-c= stuff (I always forget those).

#+BEGIN_SRC elisp
(map! :after fountain-mode
      :map fountain-mode-map
      :localleader
      :prefix ("e" . "export")

      :desc "Export Fountain file"
      "e" #'fountain-export-command)
(map! :after fountain-mode
      :map fountain-mode-map
      :localleader
      :prefix ("e" . "export")

      :desc "Export to PDF using Troff"
      "t" #'fountain-export-troff)
#+END_SRC

* LaTeX
This line fixes an issue with Emacs < 30 that prevented AucTeX from working correctly with Doom Emacs. I have no idea about why, but this solution came up [[https://discourse.doomemacs.org/t/auctex-and-latex-mode/4901/3][online]]...
#+begin_src emacs-lisp :tangle yes
(setq major-mode-remap-alist major-mode-remap-defaults)
#+end_src

* Python
** Ruff and Ruff Language Server
#+begin_src elisp
(add-hook 'python-mode-hook 'eglot-ensure)
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(python-mode . ("ruff" "server")))
  (add-hook 'after-save-hook 'eglot-format))
#+end_src

* RSS Reader
#+BEGIN_SRC elisp :tangle packages.el
(package! elfeed)
(package! elfeed-goodies)
(package! elfeed-org)
(package! elfeed-tube)
(package! elfeed-tube-mpv)
#+END_SRC

#+BEGIN_SRC elisp
(require 'elfeed-goodies)
(elfeed-goodies/setup)
(require 'elfeed-org)
(elfeed-org)
(add-hook! 'elfeed-search-mode-hook #'elfeed-update)
#+END_SRC

#+BEGIN_SRC elisp
(use-package! elfeed
  :commands elfeed
  :init
  (map! :leader
    (:prefix ("o" . "open")
      :desc "Open elfeed" "e" #'elfeed)))
(after! elfeed
  (map! :map elfeed-search-mode-map
        :localleader
        :desc "Elfeed update" "r" #'elfeed-update))
(use-package! elfeed-web
    :defer t
    :commands elfeed-web-stop)

(map! :after elfeed-search
      :map elfeed-search-mode-map
      [remap kill-this-buffer] "q"
    [remap kill-buffer] "q"
    :n "q" #'elfeed-kill-buffer
)
#+END_SRC

* Accounting Software
To manage my money, I use =hledger=. To edit the journal file without leaving Emacs, I use =ledger-mode= (I prefer it to =hledger-mode=).

I leverage the script provided in the [[https://hledger.org/editors.html#hledger-mode][=hledger= documentation]] to fully make this functional.

#+begin_src shell :tangle hledger.sh :shebang "#!/bin/sh"
# hledger.sh
# Kudos to acarrico for the original script.

# The script is contingent on ledger-default-date-string
# being set to "%Y-%m-%d", aka ISO date format.

iargs=("$@")
oargs=()
j=0;
date=;
for((i=0; i<${#iargs[@]}; ++i)); do
    case ${iargs[i]} in
        --date-format)
            # drop --date-format and the next arg
            i=$((i+1));
            ;;
        cleared) # for ledger-di
            splay-balance-at-point
            # convert "cleared" to "balance -N -C"
            oargs[j]=balance; oargs[j+1]=-N; oargs[j+2]=-C; j=$((j+3));
            ;;
        xact)
            # convert "xact" to "print --match"
            oargs[j]=print; oargs[j+1]=--match; j=$((j+2));
            # drop xact argument and stash the date argument
            i=$((i+1));
            date=${iargs[i]};
            ;;
        # NOTE: Reconciliation still doesn't work for other reasons
        #       so the following filters/conversions are unnecessary for now.
        # --sort) # for reconcilliation
        #     # drop --sort and the next arg
        #     i=$((i+1));
        #     ;;
        # --uncleared) # for reconcilliation
        #     # convert "--uncleared" to "--unmarked --pending"
        #     oargs[j]=--unmarked; oargs[j+1]=--pending; j=$((j+2))
        #     ;;
        *)
            # keep any other args:
            oargs[j]=${iargs[i]};
            j=$((j+1));
            ;;
    esac
done

if test "$date"
then
    # substitute the given date for the old date:
    hledger "${oargs[@]}" | sed "1s/....-..-../$date/"
else
    # echo "${oargs[@]}"
    hledger "${oargs[@]}"
fi
#+end_src


#+begin_src sh
realpath hledger.sh
#+end_src

#+NAME: hledger-script-file-path
#+RESULTS:
: /Users/andreaesposito/.config/doom/hledger.sh


To make =ledger-mode= compatible with =hledger= I need to change the default date format.

#+begin_src elisp :var hledger_script_path=hledger-script-file-path
(use-package! ledger-mode
  :custom
  ((ledger-binary-path "hledger")
   (ledger-mode-should-check-version nil)
   (ledger-report-auto-width nil)
   (ledger-report-links-in-register nil)
   (ledger-report-native-highlighting-arguments '("--color=always")))
  :mode ("\\.hledger\\.journal\\'" . ledger-mode))
(setq ledger-default-date-format "%Y-%m-%d")
(setq ledger-binary-path hledger_script_path)
#+end_src
